### ISSUE TITLE
How to change language to english or french?

### ISSUE THREAD

**Issue by hervehobbes** [mjun/gnome-connection-manager#2]
Hello,

Is there a way to change the program's language, from its configuration for example.
I don't inderstand the language used by the program.

**Comment by mjun** [comment]
Try running gnome-connection-manager.py prefixed with LANGUAGE variable, like so:
```
$ LANGUAGE=en_US:en python gnome_connection_manager.py
```

I'll add language settings to GUI when I find some spare time.

**Comment by hervethouzard** [comment]
Thanks for your answer.
I tried this but it still does not change the language:
LANGUAGE=fr_FR:fr python gnome_connection_manager.py

**Comment by mjun** [comment]
How about this?
```
$ LANG=fr_FR.UTF-8 python gnome_connection_manager.py
```

**Comment by hervethouzard** [comment]
No change.
I'm using Ubuntu 16.04 and Python 2.7.12

**Comment by sirkuttin** [comment]
I am having the same issue with english. Tested the method above with no success.

**Comment by sirkuttin** [comment]
@hervehobbes i forked this and swapped everything to english https://github.com/sirkuttin/gnome-connection-manager/

@mjun The ability to select default language in the UI will be great. I just did this fork so I can start using it right away.

**Comment by hervehobbes** [comment]
@sirkuttin Thanks

**Comment by Thesee** [comment]
You should convert the .po file to mo, then you have tu put it on lang/{locale}/LC_MESSAGES/{app_name}.mo
eg: lang/en_US/LC_MESSAGES/gcm-lang.mo

Regards
P.S. if you are not able to convert .po to .mo with your system, use online service, google is your friend ;)

**Comment by mjun** [comment]
Problems with translations are now fixed. Please check out the latest version. I've also updated README with instructions how to use specific language.
