### ISSUE TITLE
how to define startup dir for local

### ISSUE THREAD

**Issue by ericiper** [mjun/gnome-connection-manager#4]
Hello
Many thanks for taking over the project !
Is there a way to specify the startup dir when launching a local console ? I've added Path= to the .desktop file, but no success !
E.

**Comment by mjun** [comment]
Hi,
local terminals will respect whatever you have defined in your `~./bashrc` file. For all local terminals to start, for example, in ~/Downloads you could just add "cd ~/Downloads" to your bashrc. But I'll consider adding it as a setting also.

**Comment by ericiper** [comment]
Hadnt thought of it ! Thanks, and thanks again for continuing this project !
